<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class SiswaCtrl extends \REST_Controller {

	function __construct()
    {
        parent::__construct();
        $this->methods['data_get']['limit'] = 500; // 500 requests per hour per user/key
        $this->methods['data_post']['limit'] = 100; // 100 requests per hour per user/key
        $this->methods['data_delete']['limit'] = 50; // 50 requests per hour per user/key
        $this->load->model([siswa_m]);
    }

    public function data_get()
    {
        $siswas = $this->siswa_m->get()->toArray();
        $id = $this->get('id');
        if ($id === NULL) {
            if ($siswas) {
                $this->response($siswas, REST_Controller::HTTP_OK);
            } else {
                $this->response([
                    'status' => FALSE,
                    'message' => 'No siswas were found'
                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
            }
        } else {
            $id = (int) $id;
            if ($id <= 0) {
                $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
            }
            $siswa = NULL;
            if (!empty($siswas)) {
                foreach ($siswas as $key => $value) {
                    if (isset($value['id']) && $value['id'] === $id)
                    {
                        $siswa = $value;
                    }
                }
            }
            if (!empty($siswa)) {
                $this->set_response($siswa, REST_Controller::HTTP_OK); // OK (200) being the HTTP response code
            } else {
                $this->set_response([
                    'status' => FALSE,
                    'message' => 'siswa could not be found'
                ], REST_Controller::HTTP_NOT_FOUND); // NOT_FOUND (404) being the HTTP response code
            }
        }
    }

    public function data_post()
    {
        $message = [
            'id' => 100, // Automatically generated by the model
            'name' => $this->post('name'),
            'email' => $this->post('email'),
            'message' => 'Added a resource'
        ];
        $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
    }

    public function data_delete()
    {
        $id = (int) $this->get('id');
        if ($id <= 0) {
            $this->response(NULL, REST_Controller::HTTP_BAD_REQUEST); // BAD_REQUEST (400) being the HTTP response code
        }
        $message = [
            'id' => $id,
            'message' => 'Deleted the resource'
        ];
        $this->set_response($message, REST_Controller::HTTP_NO_CONTENT); // NO_CONTENT (204) being the HTTP response code
    }
}
